# =====================================================================
# ECO MONITOR — USER.PY (MODEL)
# Purpose: Defines the SQLAlchemy ORM schema for the "users" table.
# =====================================================================

# Import Base from backend/db/base
# WHY:
# - Base contains the SQLAlchemy metadata mapping Python classes to SQL tables
from backend.db.base import Base

# Import SQLAlchemy Column types and fields
# WHY:
# - String: Stores textual data (username, email, hash, name, role)
# - DateTime: Stores dates and times (created_at, updated_at)
from sqlalchemy import Column, String, DateTime

# Import func from sqlalchemy
# WHY:
# - Allows using database-native functions (like NOW() or CURRENT_TIMESTAMP)
from sqlalchemy import func

# Import uuid module
# WHY:
# - Used to generate universally unique identifiers (UUIDs) for primary keys
import uuid


class User(Base):
    # Specify the name of the database table
    # WHY:
    # - Tells SQLAlchemy to map this class to the "users" table in SQL
    __tablename__ = "users"

    # UUID Primary Key
    # WHY:
    # - UUIDs are globally unique, secure, and prevent enumeration attacks (unlike auto-incrementing IDs)
    # - We store it as a String of 36 characters (UUID standard) for cross-compatibility between Postgres and SQLite
    id = Column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
        index=True
    )

    # Username Column
    # WHY:
    # - Unique: Prevents multiple users from choosing the same handle
    # - Index: Optimizes lookups during authentication and queries
    username = Column(String(50), unique=True, nullable=False, index=True)

    # Email Column
    # WHY:
    # - Unique: Avoids duplicate registrations with the same email
    # - Nullable=False: Required for password resets and communications
    email = Column(String(100), unique=True, nullable=False)

    # Hashed Password Column
    # WHY:
    # - Stores the secure hash generated by security.py, NEVER plain-text passwords
    hashed_password = Column(String(255), nullable=False)

    # Full Name Column
    # WHY:
    # - Optional field representing the user's human-readable name
    name = Column(String(100), nullable=True)

    # Role Column
    # WHY:
    # - Supports Role-Based Access Control (RBAC) (INVESTOR, AUDITOR, ADMIN)
    # - Defaults to "INVESTOR" for standard users
    role = Column(String(20), nullable=False, default="INVESTOR")

    # Created At Timestamp
    # WHY:
    # - Tracks when the user registered
    # - func.now() defaults to DB-side current timestamp
    created_at = Column(DateTime, nullable=False, default=func.now())

    # Updated At Timestamp
    # WHY:
    # - Tracks when user metadata was last changed
    # - onupdate=func.now() automatically updates the timestamp when the row changes
    updated_at = Column(DateTime, nullable=False, default=func.now(), onupdate=func.now())
